albumy/forms/user.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, HiddenField, ValidationError
from wtforms.validators import DataRequired, Length, Email, EqualTo, Optional, Regexp

from albumy.models import User


class EditProfileForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(1, 30)])
    username = StringField('Username', validators=[DataRequired(), Length(1, 20),
                                                   Regexp('^[a-zA-Z0-9]*$',
                                                          message='The username should contain only a-z, A-Z and 0-9.')])
    website = StringField('Website', validators=[Optional(), Length(0, 255)])
    location = StringField('City', validators=[Optional(), Length(0, 50)])
    bio = TextAreaField('Bio', validators=[Optional(), Length(0, 120)])
    submit = SubmitField()

    def validate_username(self, field):
        if field.data != current_user.username and User.query.filter_by(username=field.data).first():
            raise ValidationError('The username is already in use.')


class EditDoctorInfoForm(FlaskForm):
    cv = StringField('CV', validators=[DataRequired(), Length(1, 150)])
    address = StringField('Address of Hospital', validators=[DataRequired()])
    speciality = StringField('Speciality', validators=[DataRequired()])
    submit = SubmitField()
    

class UploadAvatarForm(FlaskForm):
    image = FileField('Upload', validators=[
        FileRequired(),
        FileAllowed(['jpg', 'png'], 'The file format should be .jpg or .png.')
    ])
    submit = SubmitField()


class CropAvatarForm(FlaskForm):
    x = HiddenField()
    y = HiddenField()
    w = HiddenField()
    h = HiddenField()
    submit = SubmitField('Crop and Update')


class ChangeEmailForm(FlaskForm):
    email = StringField('New Email', validators=[DataRequired(), Length(1, 254), Email()])
    submit = SubmitField()

    def validate_email(self, field):
        if User.query.filter_by(email=field.data.lower()).first():
            raise ValidationError('The email is already in use.')


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('Old Password', validators=[DataRequired()])
    password = PasswordField('New Password', validators=[
        DataRequired(), Length(8, 128), EqualTo('password2')])
    password2 = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField()


class NotificationSettingForm(FlaskForm):
    receive_comment_notification = BooleanField('New comment')
    receive_follow_notification = BooleanField('New follower')
    receive_collect_notification = BooleanField('New collector')
    submit = SubmitField()


class PrivacySettingForm(FlaskForm):
    public_collections = BooleanField('Public my collection')
    submit = SubmitField()


class DeleteAccountForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(1, 20)])
    submit = SubmitField()

    def validate_username(self, field):
        if field.data != current_user.username:
            raise ValidationError('Wrong username.')

albumy/blueprints/main.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""

import requests
import stripe
from flask import render_template, flash, redirect, send_from_directory, request, abort, Blueprint
from flask_login import login_required, current_user
from sqlalchemy.sql.expression import func

from albumy import settings
from albumy.decorators import confirm_required, permission_required, role_required
from albumy.emails import send_invite_email
from albumy.forms.main import DescriptionForm, TagForm, CommentForm, WithdrawForm
from albumy.models import *
from albumy.notifications import *
from albumy.settings import Operations
from albumy.utils import rename_image, resize_image, redirect_back, flash_errors, generate_token

os.environ['SECRET_KEY'] = settings.BaseConfig.STRIPE_SECRET_KEY
os.environ['PUBLISHABLE_KEY'] = settings.BaseConfig.STRIPE_PUBLISH_KEY
stripe_keys = {
    'secret_key': os.environ['SECRET_KEY'],
    'publishable_key': os.environ['PUBLISHABLE_KEY']
}

stripe.api_key = stripe_keys['secret_key']
main_bp = Blueprint('main', __name__)


@main_bp.route('/prev_home')
def prev_index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']
        pagination = Photo.query \
            .join(Follow, Follow.followed_id == Photo.author_id) \
            .filter(Follow.follower_id == current_user.id) \
            .order_by(Photo.timestamp.desc()) \
            .paginate(page, per_page)
        photos = pagination.items

    else:
        pagination = None
        photos = None
    tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)
    return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags, Collect=Collect)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']

        tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)        
        if current_user.role.name == 'Doctor':
            doctors = Doctor.query.all()
            print("==============")
            if not current_user.confirmed:
                return redirect(url_for('user.index', username=current_user.username))
            if not (current_user.doctor.address and current_user.doctor.cv and current_user.doctor.speciality):
                return redirect(url_for('user.edit_doctor_info'))
            pagination = current_user.following.paginate(page, per_page)
            followings = pagination.items
            awards = current_user.awards
            awards_value = 0
            for award in awards:
                awards_value = awards_value + award.rate_value
            print(current_user.doctor.balance)
            balance = current_user.doctor.balance
            if not current_user.doctor.balance:
                balance = 0.00
            return render_template('main/doctor_index.html', pagination=pagination, followings=followings, tags=tags,
                                   awards_value=awards_value, doctors=doctors, balance = balance)
        if current_user.role.name == 'Patient':
            return redirect(url_for('user.index', username=current_user.username))
            # photos = current_user.photos
            # photos_id_list = [item.id for item in photos]

            # pagination = Comment.query.filter(Comment.photo_id.in_(photos_id_list)).order_by(Comment.timestamp.desc()).paginate(page, per_page)
            # comments = pagination.items
            # return render_template('main/patient_index.html', pagination=pagination,
            # comments=comments, tags=tags,photos = photos,doctors=doctors)
        else:
            pagination = Photo.query \
                .join(Follow, Follow.followed_id == Photo.author_id) \
                .filter(Follow.follower_id == current_user.id) \
                .order_by(Photo.timestamp.desc()) \
                .paginate(page, per_page)
            photos = pagination.items
            return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags)
    else:
        pagination = None
        followings = None

    return render_template('main/index.html')


@main_bp.route('/agreement')
def agreement():
    return render_template('main/agreement.html')


@main_bp.route('/terms')
def terms():
    return render_template('main/terms.html')


@main_bp.route('/explore')
def explore():
    photos = Photo.query.order_by(func.random()).limit(12)
    return render_template('main/explore.html', photos=photos)


@main_bp.route('/search')
def search():
    q = request.args.get('q', '').strip()
    if q == '':
        flash('Enter keyword about photo, user or tag.', 'warning')
        return redirect_back()

    category = request.args.get('category', 'photo')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_SEARCH_RESULT_PER_PAGE']
    if category == 'user':
        pagination = User.query.whooshee_search(q).paginate(page, per_page)
    elif category == 'tag':
        pagination = Tag.query.whooshee_search(q).paginate(page, per_page)
    else:
        pagination = Photo.query.whooshee_search(q).paginate(page, per_page)
    results = pagination.items
    return render_template('main/search.html', q=q, results=results, pagination=pagination, category=category)


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('Notification archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notifications/read/all', methods=['POST'])
@login_required
def read_all_notification():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('All notifications archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['ALBUMY_UPLOAD_PATH'], filename)


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    if not filename:
        return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], 'default.png')
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('UPLOAD')
def upload():
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')
        filename = rename_image(f.filename)
        f.save(os.path.join(current_app.config['ALBUMY_UPLOAD_PATH'], filename))
        filename_s = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['small'])
        filename_m = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['medium'])
        photo = Photo(
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object()
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')


@main_bp.route('/photo/<int:photo_id>')
@login_required
@confirm_required
def show_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(photo).order_by(Comment.timestamp.asc()).paginate(page, per_page)
    comments = pagination.items
    comment_form = CommentForm()
    description_form = DescriptionForm()
    tag_form = TagForm()

    description_form.description.data = photo.description
    if current_user.role.name != 'Doctor':
        doctors_leave_comment = []
        doctor_ids_leave_comment = []
        for comment in photo.comments:
            print(comment.author)
            if not comment.author in doctors_leave_comment:
                if comment.author.role.name == 'Doctor':
                    doctors_leave_comment.append(comment.author)
                    doctor_ids_leave_comment.append(comment.author.id)
        doctors_not_leave_comment = User.query.join(Role).filter(Role.name == 'Doctor').filter(
            ~User.id.in_(doctor_ids_leave_comment)).all()

        return render_template('main/photo.html', photo=photo, comment_form=comment_form,
                               description_form=description_form, tag_form=tag_form,
                               pagination=pagination, comments=comments, doctors_leave_comment=doctors_leave_comment,
                               doctors_not_leave_comment=doctors_not_leave_comment)
    else:
        invite = photo.invites.filter(Invite.user_id == current_user.id, Invite.status == False).first()

albumy/templates/user/_header.html
{% from 'macros.html' import follow_area with context %}
{% from 'bootstrap/nav.html' import render_nav_item %}


<div class="row">
    <div class="col-md-3">
        <a href="{% if current_user == user %}{{ url_for('.change_avatar') }}{% else %}#{% endif %}"
           title="Change avatar">
            <img class="img-fluid rounded" src="{{ url_for('main.get_avatar', filename=user.avatar_l) }}">
        </a>
    </div>
    <div class="col-md-9">
        <h1>{% if user.role.name == 'Doctor' %} Dr. {% endif %}
            {{ user.name }}
            <small class="text-muted">{{ user.username }}</small>
        </h1>
        {% if user.bio %}<p>{{ user.bio }}</p>{% endif %}
        <p>
            {% if user.website %}
                <span class="oi oi-link-intact"></span>
                <a href="{{ user.website }}" target="_blank">{{ user.website|truncate(30) }}</a>&nbsp;&nbsp;
            {% endif %}
            {% if user.location %}
                <span class="oi oi-map-marker"></span>
                <a href="https://www.google.com/maps?q={{ user.location }}"
                   target="_blank">{{ user.location|truncate(30) }}</a>&nbsp;&nbsp;
            {% endif %}
            <span class="oi oi-calendar"></span>
            Joined {{ moment(user.member_since).format('LL') }}
        </p>
        <div>
            {% if current_user != user %}
                {% if current_user.can('MODERATE') %}
                    {% if user.locked %}
                        <form class="inline" action="{{ url_for('admin.unlock_user', user_id=user.id) }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-secondary btn-sm" value="Unlock">
                        </form>
                    {% else %}
                        <form class="inline" action="{{ url_for('admin.lock_user', user_id=user.id) }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-warning btn-sm" value="Lock">
                        </form>
                    {% endif %}
                    {% if user.active %}
                        <form class="inline" action="{{ url_for('admin.block_user', user_id=user.id) }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-warning btn-sm" value="Block">
                        </form>
                    {% else %}
                        <form class="inline" action="{{ url_for('admin.unblock_user', user_id=user.id) }}"
                              method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-secondary btn-sm" value="Unblock">
                        </form>
                    {% endif %}
                    <a class="btn btn-light btn-sm" href="mailto:{{ user.email }}">Email</a>
                {% endif %}

                {% if current_user.is_admin %}
                    <a class="btn btn-warning btn-sm" href="{{ url_for('admin.edit_profile_admin', user_id=user.id) }}">Edit
                        profile</a>
                {% endif %}
            {% endif %}
            <div class="float-right">
                {{ follow_area(user) }}
                {% if current_user.is_authenticated and user == current_user %}
                    <a class="btn btn-outline-primary btn-sm" href="{{ url_for('.edit_profile') }}">Edit profile</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="user-nav">
    <ul class="nav nav-tabs">
        {{ render_nav_item('user.index', 'Photo', user.photos|length, username=user.username) }}
        {{ render_nav_item('user.show_collections', 'Collections', user.collections|length, username=user.username) }}
        {{ render_nav_item('user.show_following', 'Following', user.following.count() - 1, username=user.username) }}
        {{ render_nav_item('user.show_followers', 'Follower', user.followers.count() - 1, username=user.username) }}
        {{ render_nav_item('user.tags', 'Tags', username=user.username) }}
        {% if user.role.name == 'Doctor' %}
            {{ render_nav_item('user.show_invites', 'Invites',user.invites.count(), username=user.username) }}
        {% endif %}
    </ul>
</div>

albumy/templates/user/collections.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card %}

{% block title %}{{ user.name }}'s collection{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if user.public_collections or current_user == user %}
                {% if collects %}
                    {% for collect in collects %}
                        {{ photo_card(collect.collected) }}
                    {% endfor %}
                {% else %}
                    <div class="tip">
                        <h3>No collection.</h3>
                    </div>
                {% endif %}
            {% else %}
                <div class="tip">
                    <h3>This user's collections was private.</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if collects %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock %}

albumy/templates/user/followers.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}{{ user.name }}'s followers{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if follows|length != 1 %}
                {% for follow in follows %}
                    {% if follow.follower != user %}
                        {{ user_card(user=follow.follower) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h3>No followers.</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if follows|length != 1 %}
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}

albumy/templates/user/following.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}{{ user.name }}'s following{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if follows|length != 1 %}
                {% for follow in follows %}
                    {% if follow.followed != user %}
                        {{ user_card(user=follow.followed) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h3>No followings.</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if follows|length != 1 %}
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}

albumy/templates/user/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card %}

{% block title %}{{ user.name }}{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}    
    <div class="row">
        <div class="col-md-12">
            {% if photos %}
                {% for photo in photos %}
                    {{ photo_card(photo) }}
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>No photos.</h3>
                    {% if user == current_user %}
                        <a class="btn btn-link" href="{{ url_for('main.upload') }}">Upload</a>
                    {% else %}
                        <a class="btn btn-link" href="{{ url_for('main.explore') }}">Explore</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
    {% if photos %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock %}

albumy/templates/user/invites.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}{{ user.name }}'s following{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-9">

            {% if invites|length > 0  %}
                {% for invite in invites %}
                    {% if invite.status %}
                       <p class="ml-4">You have received the invite request from <strong>{{ invite.photo.author.name }} for Photo {{ invite.photo_id }}</strong></p>
                    {% else %}
                        <a href="{{ url_for('main.show_photo',photo_id = invite.photo_id) }}"><p class="ml-4">You have received the invite request from <strong>{{ invite.photo.author.name }} </strong> for Photo {{ invite.photo_id }} </p></a>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h3>No Invites.</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if invites|length != 1 %}
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}

albumy/templates/user/opinions.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}
{% from 'macros.html' import follow_area with context %}
{% from 'macros.html' import photo_card %}
{% block title %}{{ user.name }}'s following{% endblock %}
{% block styles %}
    {{super()}}
    <style type="text/css">
        .comment-photo{
            width: 100%;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            <a href="{% if current_user == user %}{{ url_for('.change_avatar') }}{% else %}#{% endif %}"
               title="Change avatar">
                <img class="img-fluid rounded" src="{{ url_for('main.get_avatar', filename=user.avatar_l) }}">
            </a>
        </div>
        <div class="col-md-9">
            <h1>{{ user.name }}
                <small class="text-muted">{{ user.username }}</small>
            </h1>
            {% if user.bio %}<p>{{ user.bio }}</p>{% endif %}
            <p>
                {% if user.website %}
                    <span class="oi oi-link-intact"></span>
                    <a href="{{ user.website }}" target="_blank">{{ user.website|truncate(30) }}</a>&nbsp;&nbsp;
                {% endif %}
                {% if user.location %}
                    <span class="oi oi-map-marker"></span>
                    <a href="https://www.google.com/maps?q={{ user.location }}"
                       target="_blank">{{ user.location|truncate(30) }}</a>&nbsp;&nbsp;
                {% endif %}
                <span class="oi oi-calendar"></span>
                Joined {{ moment(user.member_since).format('LL') }}
            </p>
            <div>
                {% if current_user != user %}
                    {% if current_user.can('MODERATE') %}
                        {% if user.locked %}
                            <form class="inline" action="{{ url_for('admin.unlock_user', user_id=user.id) }}" method="post">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <input type="submit" class="btn btn-secondary btn-sm" value="Unlock">
                            </form>
                        {% else %}
                            <form class="inline" action="{{ url_for('admin.lock_user', user_id=user.id) }}" method="post">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <input type="submit" class="btn btn-warning btn-sm" value="Lock">
                            </form>
                        {% endif %}
                        {% if user.active %}
                            <form class="inline" action="{{ url_for('admin.block_user', user_id=user.id) }}" method="post">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <input type="submit" class="btn btn-warning btn-sm" value="Block">
                            </form>
                        {% else %}
                            <form class="inline" action="{{ url_for('admin.unblock_user', user_id=user.id) }}"
                                  method="post">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <input type="submit" class="btn btn-secondary btn-sm" value="Unblock">
                            </form>
                        {% endif %}
                        <a class="btn btn-light btn-sm" href="mailto:{{ user.email }}">Email</a>
                    {% endif %}

                    {% if current_user.is_admin %}
                        <a class="btn btn-warning btn-sm" href="{{ url_for('admin.edit_profile_admin', user_id=user.id) }}">Edit
                            profile</a>
                    {% endif %}
                {% endif %}
                <div class="float-right">
                    {{ follow_area(user) }}
                    {% if current_user.is_authenticated and user == current_user %}
                        <a class="btn btn-outline-primary btn-sm" href="{{ url_for('.edit_profile') }}">Edit profile</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <h4>The Opinions that you give to the Patient {{user.name}}</h4>
    </div>
    <div id="comments">
        {% if comments %}
            {% for comment in comments %}
            <div class="row mt-2" style="border-width: 1px;border-style: solid;border-color: rgba(0, 0, 0, 0.125)">
                <div class="col-md-10" >
                    <span>{{ comment.timestamp.strftime('%Y/%m/%d') }}</span>
                    <div class="ml-2">
                        {{comment.body}}
                    </div>
                </div>
                <div class="col-md-2 comment-photo">
                    <a href="{{ url_for('main.show_photo', photo_id=comment.photo.id) }}">
                        <img class="card-img-top portrait" src="{{ url_for('main.get_image', filename=comment.photo.filename_s) }}">
                    </a>
                    <div>
                        <span class="oi oi-star"></span> {{ comment.photo.collectors|length }}
                        <span class="oi oi-comment-square"></span> {{ comment.photo.comments|length }}
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="tip">
                <h3>No followings.</h3>
            </div>
        {% endif %}
    </div>
    {% if follows|length != 1 %}
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}

albumy/templates/user/tags.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}{{ user.name }}'s following{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}

    <div class="row">
        <div class="col-md-12">
            {% if tags %}
                {% for tag in tags %}
      
                    <a class="badge badge-light"
                       href="{{ url_for('main.show_tag', tag_id=tag.id) }}" target="_blank"><span
                            class="oi oi-tag"></span> {{ tag.name }}</a>
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h3>No Tags.</h3>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}