albumy/forms/main.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FloatField
from wtforms.validators import DataRequired, Optional, Length, NumberRange
from wtforms.validators import ValidationError
from flask_login import current_user

class DescriptionForm(FlaskForm):
    description = TextAreaField('Description', validators=[Optional(), Length(0, 500)])
    submit = SubmitField()


class TagForm(FlaskForm):
    tag = StringField('Add Tag (use space to separate)', validators=[Optional(), Length(0, 64)])
    submit = SubmitField()


class CommentForm(FlaskForm):
    body = TextAreaField('', validators=[DataRequired()])
    submit = SubmitField()


class WithdrawForm(FlaskForm):
    amount = FloatField('Amount')
    bank_code = StringField('Bank Code', validators=[DataRequired(), Length(0, 255)])
    branch_code = StringField('Branch Code', validators=[ DataRequired(), Length(0, 255)])
    account_number = StringField('Account Number', validators=[DataRequired(), Length(0, 255)])
    additional_info = TextAreaField('Additional Info', validators=[Optional()])
    submit = SubmitField()
    def validate_amount(form,field):
        if not current_user.doctor:
            return
        balance = current_user.doctor.balance
        if not current_user.doctor.balance:
            raise ValidationError('You don\'t have enough Money')
        if float(field.data) > balance:
            raise ValidationError('Your Withdraw Request Amount is bigger than your Balance')
        elif float(field.data) < 0 :
            raise ValidationError('Your Withdraw Request Amount must be bigger than 0')

albumy/blueprints/ajax.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask import render_template, jsonify, Blueprint
from flask_login import current_user

from albumy.models import User, Photo, Notification
from albumy.notifications import push_collect_notification, push_follow_notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)


@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1  # minus user self
    return jsonify(count=count)


@ajax_bp.route('/<int:photo_id>/followers-count')
def collectors_count(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    count = len(photo.collectors)
    return jsonify(count=count)


@ajax_bp.route('/collect/<int:photo_id>', methods=['POST'])
def collect(photo_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:
        return jsonify(message='Confirm account required.'), 400
    if not current_user.can('COLLECT'):
        return jsonify(message='No permission.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if current_user.is_collecting(photo):
        return jsonify(message='Already collected.'), 400

    current_user.collect(photo)
    if current_user != photo.author and photo.author.receive_collect_notification:
        push_collect_notification(collector=current_user, photo_id=photo_id, receiver=photo.author)
    return jsonify(message='Photo collected.')


@ajax_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
def uncollect(photo_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if not current_user.is_collecting(photo):
        return jsonify(message='Not collect yet.'), 400

    current_user.uncollect(photo)
    return jsonify(message='Collect canceled.')


@ajax_bp.route('/follow/<username>', methods=['POST'])
def follow(username):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:
        return jsonify(message='Confirm account required.'), 400
    if not current_user.can('FOLLOW'):
        return jsonify(message='No permission.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        return jsonify(message='Already followed.'), 400

    current_user.follow(user)
    if user.receive_collect_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return jsonify(message='User followed.')


@ajax_bp.route('/unfollow/<username>', methods=['POST'])
def unfollow(username):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_following(user):
        return jsonify(message='Not follow yet.'), 400

    current_user.unfollow(user)
    return jsonify(message='Follow canceled.')

albumy/blueprints/main.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""

import requests
import stripe
from flask import render_template, flash, redirect, send_from_directory, request, abort, Blueprint
from flask_login import login_required, current_user
from sqlalchemy.sql.expression import func

from albumy import settings
from albumy.decorators import confirm_required, permission_required, role_required
from albumy.emails import send_invite_email
from albumy.forms.main import DescriptionForm, TagForm, CommentForm, WithdrawForm
from albumy.models import *
from albumy.notifications import *
from albumy.settings import Operations
from albumy.utils import rename_image, resize_image, redirect_back, flash_errors, generate_token

os.environ['SECRET_KEY'] = settings.BaseConfig.STRIPE_SECRET_KEY
os.environ['PUBLISHABLE_KEY'] = settings.BaseConfig.STRIPE_PUBLISH_KEY
stripe_keys = {
    'secret_key': os.environ['SECRET_KEY'],
    'publishable_key': os.environ['PUBLISHABLE_KEY']
}

stripe.api_key = stripe_keys['secret_key']
main_bp = Blueprint('main', __name__)


@main_bp.route('/prev_home')
def prev_index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']
        pagination = Photo.query \
            .join(Follow, Follow.followed_id == Photo.author_id) \
            .filter(Follow.follower_id == current_user.id) \
            .order_by(Photo.timestamp.desc()) \
            .paginate(page, per_page)
        photos = pagination.items

    else:
        pagination = None
        photos = None
    tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)
    return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags, Collect=Collect)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']

        tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)        
        if current_user.role.name == 'Doctor':
            doctors = Doctor.query.all()
            print("==============")
            if not current_user.confirmed:
                return redirect(url_for('user.index', username=current_user.username))
            if not (current_user.doctor.address and current_user.doctor.cv and current_user.doctor.speciality):
                return redirect(url_for('user.edit_doctor_info'))
            pagination = current_user.following.paginate(page, per_page)
            followings = pagination.items
            awards = current_user.awards
            awards_value = 0
            for award in awards:
                awards_value = awards_value + award.rate_value
            print(current_user.doctor.balance)
            balance = current_user.doctor.balance
            if not current_user.doctor.balance:
                balance = 0.00
            return render_template('main/doctor_index.html', pagination=pagination, followings=followings, tags=tags,
                                   awards_value=awards_value, doctors=doctors, balance = balance)
        if current_user.role.name == 'Patient':
            return redirect(url_for('user.index', username=current_user.username))
            # photos = current_user.photos
            # photos_id_list = [item.id for item in photos]

            # pagination = Comment.query.filter(Comment.photo_id.in_(photos_id_list)).order_by(Comment.timestamp.desc()).paginate(page, per_page)
            # comments = pagination.items
            # return render_template('main/patient_index.html', pagination=pagination,
            # comments=comments, tags=tags,photos = photos,doctors=doctors)
        else:
            pagination = Photo.query \
                .join(Follow, Follow.followed_id == Photo.author_id) \
                .filter(Follow.follower_id == current_user.id) \
                .order_by(Photo.timestamp.desc()) \
                .paginate(page, per_page)
            photos = pagination.items
            return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags)
    else:
        pagination = None
        followings = None

    return render_template('main/index.html')


@main_bp.route('/agreement')
def agreement():
    return render_template('main/agreement.html')


@main_bp.route('/terms')
def terms():
    return render_template('main/terms.html')


@main_bp.route('/explore')
def explore():
    photos = Photo.query.order_by(func.random()).limit(12)
    return render_template('main/explore.html', photos=photos)


@main_bp.route('/search')
def search():
    q = request.args.get('q', '').strip()
    if q == '':
        flash('Enter keyword about photo, user or tag.', 'warning')
        return redirect_back()

    category = request.args.get('category', 'photo')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_SEARCH_RESULT_PER_PAGE']
    if category == 'user':
        pagination = User.query.whooshee_search(q).paginate(page, per_page)
    elif category == 'tag':
        pagination = Tag.query.whooshee_search(q).paginate(page, per_page)
    else:
        pagination = Photo.query.whooshee_search(q).paginate(page, per_page)
    results = pagination.items
    return render_template('main/search.html', q=q, results=results, pagination=pagination, category=category)


@main_bp.route('/notifications')
@login_required
def show_notifications():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_NOTIFICATION_PER_PAGE']
    notifications = Notification.query.with_parent(current_user)
    filter_rule = request.args.get('filter')
    if filter_rule == 'unread':
        notifications = notifications.filter_by(is_read=False)

    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(page, per_page)
    notifications = pagination.items
    return render_template('main/notifications.html', pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    if current_user != notification.receiver:
        abort(403)

    notification.is_read = True
    db.session.commit()
    flash('Notification archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/notifications/read/all', methods=['POST'])
@login_required
def read_all_notification():
    for notification in current_user.notifications:
        notification.is_read = True
    db.session.commit()
    flash('All notifications archived.', 'success')
    return redirect(url_for('.show_notifications'))


@main_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['ALBUMY_UPLOAD_PATH'], filename)


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    if not filename:
        return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], 'default.png')
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('UPLOAD')
def upload():
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')
        filename = rename_image(f.filename)
        f.save(os.path.join(current_app.config['ALBUMY_UPLOAD_PATH'], filename))
        filename_s = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['small'])
        filename_m = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['medium'])
        photo = Photo(
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object()
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')


@main_bp.route('/photo/<int:photo_id>')
@login_required
@confirm_required
def show_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(photo).order_by(Comment.timestamp.asc()).paginate(page, per_page)
    comments = pagination.items
    comment_form = CommentForm()
    description_form = DescriptionForm()
    tag_form = TagForm()

    description_form.description.data = photo.description
    if current_user.role.name != 'Doctor':
        doctors_leave_comment = []
        doctor_ids_leave_comment = []
        for comment in photo.comments:
            print(comment.author)
            if not comment.author in doctors_leave_comment:
                if comment.author.role.name == 'Doctor':
                    doctors_leave_comment.append(comment.author)
                    doctor_ids_leave_comment.append(comment.author.id)
        doctors_not_leave_comment = User.query.join(Role).filter(Role.name == 'Doctor').filter(
            ~User.id.in_(doctor_ids_leave_comment)).all()

        return render_template('main/photo.html', photo=photo, comment_form=comment_form,
                               description_form=description_form, tag_form=tag_form,
                               pagination=pagination, comments=comments, doctors_leave_comment=doctors_leave_comment,
                               doctors_not_leave_comment=doctors_not_leave_comment)
    else:
        invite = photo.invites.filter(Invite.user_id == current_user.id, Invite.status == False).first()

albumy/templates/main/doctor_index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block title %}Home{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.theme.default.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <style type="text/css">
        #map{
            width: 100%;
            height: 400px;
            background-color: grey;
        }
    </style>
{% endblock %}
{% block content %}
{% if current_user.is_authenticated %}
<!--Start Profile Part -->
    
<!--End Profile Part  -->
    <div class="row justify-content-md-center">        
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-5 animate-box">
                    <div class="owl-carousel3">
                        <div class="item">
                            <img class="img-responsive about-img" src="{{ url_for('main.get_avatar', filename=current_user.avatar_raw) }}" alt="html5 bootstrap template by colorlib.com">
                        </div>
                        <div class="item">
                            <img class="img-responsive about-img" src="{{ url_for('main.get_avatar', filename=current_user.avatar_raw2) }}" alt="html5 bootstrap template by colorlib.com">
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-md-push-1 animate-box">
                        <h2> <span> Dr {{current_user.name}}</span></h2>
                    <ul class="personal-info">
                      <li>
                        <span> CV</span> 
                        <p>{{current_user.doctor.cv}}</p>
                      </li>
                    <li>
                        <span> Speciality</span> 
                        <p> {{current_user.doctor.speciality}}</p>
                      </li>

                      <li>
                        <span> Address</span>
                        <p> {{current_user.doctor.address}}</p>
                      </li>                      
                      <li>
                       <span> <span class="oi oi-star"></span> <font style="font-weight: normal;">{{awards_value}}</font></span>
                      </li>
                    </ul>
                    
                </div>
            </div>
            <div class="row" style="padding: .75rem">
                <h5> <span> Following:</span></h5>
            </div>
            {% if followings %}
                {% if followings|length != 1 %}
                    {% for item in followings %}
                        {% if item.followed != current_user %}
                            <div class="card mb-3 w-100 bg-light">
                                <div class="card-header">
                                    <div style="float: left;">
                                        <a class="dead-link" href="{{ url_for('user.index', username=item.followed.username) }}">
                                            <img class="rounded img-fluid avatar-s profile-popover" data-href="{{ url_for('ajax.get_profile', user_id=item.followed.id) }}" src="{{ url_for('main.get_avatar', filename=item.followed.avatar_m) }}">
                                        </a>
                                        <span class="profile-popover trend-card-avatar" data-href="{{ url_for('ajax.get_profile', user_id=item.followed.id) }}"> {{ item.followed.name }}</span>
                                       <div>
                                            <span class="oi oi-star"></span>
                                            <span class="oi oi-star"></span>
                                            <span class="oi oi-star"></span>
                                        </div>
                                    </div>
                                    
                                    <span class="float-right" style="line-height: 45px;vertical-align: middle;" >
                                        <a class="pr-2" data-href="/ajax/profile/11" href="{{ url_for('user.tags', username=item.followed.username) }}">Tags</a>
                                        <a class="pr-2" data-href="/ajax/profile/11" href="{{ url_for('user.index', username=item.followed.username) }}">Photos</a>
                                        <span>
                                            <small >
                                                {% if item.followed.last_uploaded_photo %}
                                                    {{ item.followed.last_uploaded_photo.timestamp.strftime('%Y/%m/%d') }}
                                                {% else %}
                                                    unavailable
                                                {% endif %}
                                            </small>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endif %}    
    </div>
    <div class="col-md-3">
        <div id="map"></div>
        {% include 'main/_sidebar.html' %}
    </div>

    {% if followings %}
        {{ render_pagination(pagination, align='center') }}
    {% endif %}
{% else %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
                <img src="{{ url_for('static', filename='images/index.jpg') }}" class="rounded img-fluid">
            </div>
            <div class="col-md-4 align-self-center">
                <h1>Albumy</h1>
                <p>Capture and remember every wonderful moment.</p>
                <p><a class="btn btn-primary btn-lg" href="{{ url_for('auth.register') }}">Join Now</a></p>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/jquery.waypoints.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script>
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see the error "The Geolocation service
      // failed.", it means you probably did not give permission for the browser to
      // locate you.
      var map, infoWindow;
      function initMap() {
        var geo_location = {
            lat: {{current_user.doctor.latitude}},lng: {{current_user.doctor.longitude}}
        };
        var status = '{{current_user.doctor.status}}'
        map = new google.maps.Map(document.getElementById('map'), {
          center: geo_location,          
          zoom: 6
        });
         var contentString = '<div id="content">'+
            '<div id="bodyContent">'+
            'Location Not Found Correctly'+
            '</div>'
            '</div>';
        if(status == 'OK'){
            var marker = new google.maps.Marker({position: geo_location, map: map});

        }else{
            var infowindow = new google.maps.InfoWindow({
              content: contentString,
              position:geo_location
            });
            infowindow.open(map);
        }
    }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key={{config['GOOGLE_MAP_API_KEY']}}&amp;callback=initMap" defer="" async=""> </script>
{% endblock %}

albumy/templates/main/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card with context %}

{% block title %}Home{% endblock %}

{% block content %}

{% if current_user.is_authenticated %}

    <div class="row justify-content-md-center">
        <div class="col-md-8">
            {% if photos %}
                {% for photo in photos %}
                    <div class="card mb-3 w-100 bg-light">
                        <div class="card-header">
                            <a class="dead-link" href="{{ url_for('user.index', username=photo.author.username) }}">
                                <img class="rounded img-fluid avatar-s profile-popover"
                                     data-href="{{ url_for('ajax.get_profile', user_id=photo.author.id) }}"
                                     src="{{ url_for('main.get_avatar', filename=photo.author.avatar_m) }}">
                            </a>
                            <a class="profile-popover trend-card-avatar"
                               data-href="{{ url_for('ajax.get_profile', user_id=photo.author.id) }}"
                               href="{{ url_for('user.index', username=photo.author.username) }}">{{ photo.author.name }}</a>
                            <span class="float-right">
                <small data-toggle="tooltip" data-placement="top" data-timestamp="{{ photo.timestamp }}"
                       data-delay="500">
                    {{ moment(photo.timestamp).fromNow(refresh=True) }}</small></span>
                        </div>
                        <div class="card-body">
                            <div class="" align="center">
                                <a class="thumbnail" href="{{ url_for('.show_photo', photo_id=photo.id) }}"
                                   target="_blank">
                                    <img class="img-fluid"
                                         src="{{ url_for('.get_image', filename=photo.filename_m) }}">
                                </a>
                            </div>
                        </div>
                        <div class="card-footer">
                            <span class="oi oi-star"></span>
                            <span id="collectors-count-{{ photo.id }}"
                                  data-href="{{ url_for('ajax.collectors_count', photo_id=photo.id) }}">
                                {{ photo.collectors|length }}
                            </span>
                            <span class="oi oi-comment-square"></span> {{ photo.comments|length }}
                            <div class="float-right">
                                {% if current_user.is_authenticated %}
                                    <button class="{% if not current_user.is_collecting(photo) %}hide{% endif %}
                                     btn btn-outline-secondary btn-sm uncollect-btn"
                                            data-href="{{ url_for('ajax.uncollect', photo_id=photo.id) }}"
                                            data-id="{{ photo.id }}">
                                        <span class="oi oi-x"></span> Uncollect
                                    </button>
                                    <button class="{% if current_user.is_collecting(photo) %}hide{% endif %}
                                     btn btn-outline-primary btn-sm collect-btn"
                                            data-href="{{ url_for('ajax.collect', photo_id=photo.id) }}"
                                            data-id="{{ photo.id }}">
                                        <span class="oi oi-star"></span> Collect
                                    </button>
                                {% else %}
                                    <form class="inline" method="post"
                                          action="{{ url_for('main.collect', photo_id=photo.id) }}">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-outline-primary btn-sm">
                                            <span class="oi oi-star"></span> Collect
                                        </button>
                                    </form>
                                {% endif %}
                            </div>
                            {% if photo.description %}
                                <p class="card-text">{{ photo.description }}</p>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>No trends.</h3>
                    <p><a href="{{ url_for('.explore') }}">Explore</a></p>
                </div>
            {% endif %}
        </div>
        <div class="col-md-3">
            {% include 'main/_sidebar.html' %}
        </div>
    </div>
    {% if photos %}
        {{ render_pagination(pagination, align='center') }}
    {% endif %}
{% else %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
                <img src="{{ url_for('static', filename='images/index.jpg') }}" class="rounded img-fluid">
            </div>
            <div class="col-md-4 align-self-center">
                <h1>Dr2us</h1>
                <p>Easiest way for second opinion from doctors.</p>
                <p><a class="btn btn-primary btn-lg" href="{{ url_for('auth.register') }}">Join Now</a></p>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

albumy/templates/main/profile_popup.html
<div class="popup-card">
    <img class="rounded img-fluid avatar-s popup-avatar" src="{{ url_for('main.get_avatar', filename=user.avatar_m) }}">
    <div class="popup-profile">
        <h6>{{ user.name }}</h6>
        <p class="text-muted">{{ user.username }}
            {% if current_user.is_authenticated %}
                {% if current_user != user and current_user.is_followed_by(user) %}
                    {% if user.is_followed_by(current_user) %}
                        <span class="badge badge-light">Follow each other</span>
                    {% else %}
                        <span class="badge badge-light">Follows you</span>
                    {% endif %}
                {% endif %}
            {% endif %}
        </p>
    </div>
    <p class="card-text">
        <a href="{{ url_for('user.index', username=user.username) }}">
            <strong>{{ user.photos|length }}</strong> Photos
        </a>&nbsp;
        <a href="{{ url_for('user.show_followers', username=user.username) }}">
            <strong id="followers-count-{{ user.id }}"
                    data-href="{{ url_for('ajax.followers_count', user_id=user.id) }}">
                {{ user.followers.count() - 1 }}
            </strong> Followers
        </a>
    </p>
    <a href="{{ url_for('user.index', username=user.username) }}" class="btn btn-light btn-sm">Homepage</a>
    {% if current_user.is_authenticated %}
        {% if user != current_user %}
            <button data-id="{{ user.id }}"
                    data-href="{{ url_for('ajax.unfollow', username=user.username) }}"
                    class="{% if not current_user.is_following(user) %}hide{% endif %} btn btn-dark btn-sm unfollow-btn">
                Unfollow
            </button>
            <button data-id="{{ user.id }}"
                    data-href="{{ url_for('ajax.follow', username=user.username) }}"
                    class="{% if current_user.is_following(user) %}hide{% endif %} btn btn-primary btn-sm follow-btn">
                Follow
            </button>
        {% endif %}
    {% else %}
        <form class="inline" method="post"
              action="{{ url_for('user.follow', username=user.username) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-primary btn-sm">Follow</button>
        </form>
    {% endif %}
</div>